/* ================= CONTENT DATA (EDIT TEXT HERE) ================= */
const A=n=>'/assets/'+n; // IMAGE PATHS: drop your own files into /assets and edit names below
const SV=[
{id:'staffing',n:'01',nav:'Staffing Solutions',tab:'Staffing Solutions',cap:'Staffing & Technical Manpower',img:['team.jpg','design.jpg','meeting-team.jpg'],
 core:'Our core strength — engineering, IT and technical professionals supplied for project, contract, deputation and long-term operational requirements across India.',
 all:'Staffing is where A&J started and where we are strongest. Finding the right technical professionals can be as important as finding the right technology, so every mandate is built around the exact role, skill level, location and timeline you are working with.',
 chips:['Engineering Professionals','IT Professionals','Technical Specialists','Project Resources','Support Staff'],
 lab:'01 / SERVICE - Staffing Solutions',h:'Skilled People. Right Capability.',
 secs:[['Resource Categories',['Engineering Professionals','IT Professionals','Technical Specialists','Project Resources','Support Staff','Contract / Deputation Resources']],['Engagement Models',['Project-based staffing','Contract staffing','Deputation / on-site resources','Long-term operational teams','Temp-to-permanent hiring','Bulk / volume mobilisation']],['Functional Domains',['Mechanical & production','Electrical & electronics','Design, CAD & drafting','Quality & inspection','IT, networking & support','Project & site coordination']],['What You Get From Us',['Screened, requirement-matched profiles','Fast turnaround on shortlists','Documentation & onboarding support','Replacement coordination','Single point of contact','Ongoing engagement reviews']]],
 note:'Whether you need a single specialist for a short assignment or a full technical team on deputation, our staffing model is configured around your requirement — not the other way round.',cta:'Share staffing requirement'},
{id:'it',n:'02',nav:'IT & Digital Solutions',tab:'IT & Digital Solutions',cap:'IT & Digital Solutions',img:['datacenter.jpg','itsupport.jpg','controlroom.jpg'],
 core:'End-to-end IT infrastructure and technology solutions including computing systems, servers, software, networking and enterprise IT requirements.',
 all:'A&J provides IT infrastructure and technology solutions designed to support modern organizations, projects and operational environments.',
 chips:['Desktops','Laptops','Workstations','All-in-one PCs'],lab:'02 / SERVICE',h:'IT & Digital Solutions',
 secs:[['Computing Infrastructure',['Desktops','Laptops','Workstations','All-in-one PCs']],['Servers & Infrastructure',['Servers','Storage','Networking','Infrastructure components']],['Software Solutions',['Enterprise software','Productivity solutions','Technical software','Licensing support']],['IT Support',['Installation','Configuration','Deployment','Technical support']]],cta:'Discuss your IT requirement'},
{id:'defence-engineering',n:'03',nav:'Defence & Engineering Solutions',tab:'Defence & Engineering',cap:'Defence & Engineering Solutions',img:['hangar.jpg','cnc.jpg','meeting-screen.jpg'],
 core:'Technology and engineering support for organizations operating in demanding and mission-critical environments.',
 all:'A&J Engineering Solutions supports organizations operating in technically demanding and mission-critical environments through technology, engineering support and skilled manpower capabilities.',
 chips:['Engineering Support','Technical Manpower','IT & Computing Infrastructure','Software & Technology Solutions','Project Support'],lab:'03 / SERVICE',h:'Supporting India’s Defence & Engineering Ecosystem',
 secs:[['Capabilities',['Engineering Support','Technical Manpower','IT & Computing Infrastructure','Software & Technology Solutions','Project Support','Technical Procurement']]],cta:'Discuss a project'},
{id:'gem',n:'04',nav:'GeM & Government Procurement',tab:'GeM & Procurement',cap:'GeM & Government Procurement',img:['warehouse.jpg','blueprint.jpg','meeting.jpg'],
 core:'Support for GeM cataloguing, product onboarding, government procurement requirements and tender-related activities.',
 all:'We support businesses and organizations navigating government procurement requirements, including GeM-related activities and tender-oriented processes.',
 chips:['GeM catalogue setup','Product listing support','Product documentation','OEM documentation support','Tender identification'],lab:'04 / SERVICE',h:'GeM & Government Procurement Solutions',
 secs:[['Services',['GeM catalogue setup','Product listing support','Product documentation','OEM documentation support','Tender identification','Tender documentation support','Procurement process coordination','Government marketplace support']]],note:'Our team provides professional procurement support based on the specific requirements of each engagement.',cta:'Get procurement support'},
{id:'amc',n:'05',nav:'AMC & Technical Support',tab:'AMC & Technical Support',cap:'AMC & Technical Support',img:['hardware.jpg','meeting-glass.jpg','technician.jpg'],
 core:'Reliable maintenance and technical support services designed to keep critical IT and technology infrastructure operational.',
 all:'A&J provides maintenance and technical support services designed to help organizations maintain the reliability and continuity of their technology infrastructure.',
 chips:['IT hardware AMC','Preventive maintenance','Breakdown support','Installation & configuration','Troubleshooting'],lab:'05 / SERVICE',h:'Keep Your Infrastructure Running',
 secs:[['Services',['IT hardware AMC','Preventive maintenance','Breakdown support','Installation & configuration','Troubleshooting','Technical assistance','Infrastructure support']]],cta:'Request support'}];
const PSU_TXT='A&J Engineering Solutions supports requirements across Defence, Aerospace, Government and Public Sector environments through integrated technology, engineering, manpower and procurement capabilities.';
const X={};
const ALL=[...SV.map(s=>({id:s.id,t:s.tab,d:s.id=='staffing'||1?s.core:''})),{id:'psu',t:'Defence & PSU',d:PSU_TXT}];
const $=s=>document.querySelector(s),app=$('#app');
const chips=a=>`<div class="chips">${a.map(x=>`<span class="chip">${x}</span>`).join('')}</div>`;
const em=(t,w)=>t.replace(w,`<em>${w}</em>`);
const ctaBand=(h,b1='Submit your requirement',b2='Contact A&J')=>`<section class="cta"><div class="w rv"><h2 style="max-width:720px">${h}</h2><p style="margin-top:22px;max-width:520px">Tell us what you need. Our team will understand your requirement and connect you with the appropriate solution.</p><div class="row"><a class="btn r" href="/requirement/">${b1} <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a><a class="btn" href="/contact/">${b2} <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></div></div></section>`;
/* ================= SLIDER (touch swipe, arrows, dots) ================= */
function slider(el,list,ms){el.innerHTML=list.map((x,i)=>`<${x.href?'a href="'+x.href+'"':'div'} class="s${i?'':' on'}"><img src="${A(x.img)}" alt="${x.t}" decoding="async"${i?' loading="lazy"':''}>${x.d?`<div class="cap"><b>${x.t}</b><span>${x.d}</span></div>`:''}</${x.href?'a':'div'}>`).join('')+'<i class="sh"></i><div class="cn"><b>01</b> / '+String(list.length).padStart(2,'0')+'</div><button class="ar l" aria-label="Previous">&#8592;</button><button class="ar r" aria-label="Next">&#8594;</button><div class="dt">'+list.map((x,i)=>`<button aria-label="Slide ${i+1}"${i?'':' class="on"'}></button>`).join('')+'</div>';
const s=[...el.querySelectorAll('.s')],d=[...el.querySelectorAll('.dt button')];let c=0,t,x0=0;const sh=el.querySelector('.sh'),cb=el.querySelector('.cn b');el.style.setProperty('--iv',ms+'ms');
const go=n=>{n=(n+s.length)%s.length;if(n==c)return;const o=c;el.dataset.v=n%4;s[o].classList.replace('on','pv');c=n;s[c].classList.remove('pv');void s[c].offsetWidth;s[c].classList.add('on');d.forEach((b,i)=>b.classList.toggle('on',i==c));cb.textContent=String(c+1).padStart(2,'0');sh.classList.remove('go');void sh.offsetWidth;sh.classList.add('go');setTimeout(()=>s[o].classList.remove('pv'),1100)};
const run=()=>{clearInterval(t);t=setInterval(()=>{if(!el.isConnected)return clearInterval(t);go(c+1)},ms)};
d.forEach((b,i)=>b.onclick=()=>{go(i);run()});el.querySelector('.l').onclick=()=>{go(c-1);run()};el.querySelector('.r').onclick=()=>{go(c+1);run()};
el.addEventListener('touchstart',e=>x0=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x0;if(Math.abs(dx)>40){go(c+(dx<0?1:-1));run()}});
el.onmouseenter=()=>clearInterval(t);el.onmouseleave=run;run()}
const sliderEl=(list,ms=3200,st='')=>{const e=document.createElement('div');e.className='sl';e.style.cssText=st;slider(e,list,ms);return e};
/* ================= PAGES ================= */
const SITE='https://ajengineeringsolutions.com';
const SEO={
'/':{t:'A&J Engineering Solutions | IT Services, Manpower & GeM Support',d:'A&J Engineering Solutions provides integrated technology, engineering, staffing, manpower and procurement solutions for businesses, government organizations, defence establishments and public-sector enterprises. Offices in Bangalore and Dehradun.'},
'/about':{t:'About A&J Engineering Solutions | Technology, Engineering & People',d:'A&J Engineering Solutions is an India-based technology and engineering solutions company providing integrated services across IT infrastructure, engineering support, technical manpower, defence-oriented requirements and government procurement.'},
'/services':{t:'Our Services | Staffing, IT, Defence Engineering, GeM & AMC | A&J Engineering Solutions',d:'Staffing and technical manpower, IT and digital solutions, defence and engineering solutions, GeM and government procurement support, and AMC and technical support from A&J Engineering Solutions.'},
'/staffing':{t:'Staffing & Technical Manpower Services | A&J Engineering Solutions',d:'Engineering, IT and technical professionals supplied for project, contract, deputation and long-term operational requirements across India. Manpower services for businesses, government and PSU organizations.'},
'/it':{t:'IT Hardware, Servers & Networking Services | A&J Engineering Solutions',d:'End-to-end IT infrastructure and technology solutions including computing systems, servers, software, networking and enterprise IT requirements. Offices in Bangalore and Dehradun.'},
'/defence-engineering':{t:'Defence & Engineering Solutions | A&J Engineering Solutions',d:'Technology and engineering support for organizations operating in demanding and mission-critical environments, including defence and aerospace requirements.'},
'/gem':{t:'GeM & Government Procurement Support | Catalogue & Tenders | A&J Engineering Solutions',d:'Support for GeM cataloguing, product onboarding, government procurement requirements and tender-related activities for businesses and organizations.'},
'/amc':{t:'AMC & Technical Support | IT Hardware Maintenance | A&J Engineering Solutions',d:'Reliable maintenance and technical support services designed to keep critical IT and technology infrastructure operational: IT hardware AMC, preventive maintenance and breakdown support.'},
'/psu':{t:'Defence & PSU Solutions | A&J Engineering Solutions',d:'Technology, engineering, manpower and procurement capabilities for Defence, Aerospace, Government and Public Sector environments.'},
'/contact':{t:'Contact A&J Engineering Solutions | Bangalore & Dehradun',d:'Contact A&J Engineering Solutions for project, manpower, technology or procurement requirements. Head Office in Bangalore and Branch Office in Dehradun, Uttarakhand.'},
'/requirement':{t:'Submit Your Requirement | A&J Engineering Solutions',d:'Tell us what you need. Our team will understand your requirement and connect you with the appropriate solution.'}};
const bgs=l=>`<div class="bgs" aria-hidden="true">${l.map((x,k)=>`<i style="background-image:url(${A(x)});animation-delay:${k*5}s"></i>`).join('')}</div>`;
const HV=matchMedia('(hover:hover)').matches;
const P={};
P['/']=()=>{const first=SV[0];return `<section class="hero"><div class="w wx"><div class="hg"><div><div class="eb">A&amp;J Engineering Solutions</div><h1>Staffing &amp;<br class="dbr"> Engineering solutions<br class="dbr"> for <em>All industries.</em></h1><p>A&J Engineering Solutions provides integrated technology, engineering, staffing, manpower and procurement solutions for businesses, government organizations, defence establishments and public-sector enterprises.</p><div class="row"><a class="btn r" href="/services/">Explore our services <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a><a class="lk" href="/contact/">Talk to our team &#8250;</a></div></div><div id="hs"></div></div></div></section>
<div class="w wx"><div class="tk"><span>Engineering</span><span>Technology</span><span>Staffing</span><span>Procurement</span><span>Support</span></div></div>
<section class="dv" id="dv">${ALL.map((x,i)=>`<div class="bg${i?'':' on'}" style="background-image:url(${A(['meeting.jpg','controlroom.jpg','hangar.jpg','warehouse.jpg','cnc.jpg','blueprint.jpg'][i])})"></div>`).join('')}<div class="w"><div class="tx"><div class="eb" id="dn">01 / What we deliver</div><h2 id="dt"></h2><p id="dd" style="margin-top:18px"></p><a class="lk" id="dl" href="/"></a></div></div><div class="tabs">${ALL.map((x,i)=>`<button data-i="${i}" class="${i?'':'on'}"><i>0${i+1}</i>${x.t}</button>`).join('')}</div></section>
<section><div class="w"><div class="hd rv"><div><div class="eb">02 / What we do</div><h2>Our Core <em>Capabilities</em></h2></div><p>Integrated solutions designed around the evolving requirements of technology-driven organizations.</p></div>
<div class="g3">${SV.map((s,i)=>`<article class="card rv"><div class="sl cs" data-sl="${[...s.img,...(X[s.id]||[])].join(',')}" data-t="${s.cap}"></div><i>0${i+1}</i><h3>${s.cap}</h3><p>${s.core}</p><a class="lk" href="/${s.id}/">Learn more <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></article>`).join('')}</div></div></section>
<section class="co">${bgs(['meeting.jpg','meeting-glass.jpg','meeting-team.jpg','meeting-screen.jpg'])}<div class="w"><div class="cg"><div class="rv"><div class="eb">03 / Company</div><h2>Building Solutions That Move <em>Missions Forward</em></h2></div><div class="rv"><div class="sl cg-sl" data-sl="meeting.jpg,meeting-team.jpg,meeting-screen.jpg,meeting-glass.jpg" data-t="A&J team meeting"></div><p style="color:var(--text);font-size:17px">At A&J Engineering Solutions, we bring together technology, engineering expertise, skilled professionals and procurement capabilities to help organizations execute critical requirements efficiently.</p><p>From IT infrastructure and technical manpower to defence-oriented engineering support, government procurement and GeM services, our approach is built around reliability, responsiveness and long-term partnerships.</p><p>We work closely with our clients to understand their requirements and deliver solutions that align with their operational objectives.</p><a class="btn" href="/about/">Discover A&J <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></div></div></div></section>
<section><div class="w"><div class="hd rv"><div><div class="eb">04 / Why A&amp;J</div><h2>Why Choose <em>A&amp;J?</em></h2></div><p>A requirement-first approach, backed by technical depth and responsive coordination.</p></div>
<div class="g3">${[['Requirement Driven','We begin by understanding the requirement before developing the solution.'],['Technical Capability','Our approach combines engineering understanding with technology expertise.'],['Skilled Professionals','Access to technical and professional manpower across multiple domains.'],['Government Procurement Experience','Familiarity with GeM and government procurement processes.'],['Responsive Support','Clear communication and responsive coordination throughout the engagement.'],['Long-Term Partnership','We aim to build relationships that extend beyond individual projects.']].map((x,i)=>`<div class="rv"><span class="num">0${i+1}</span><h3>${x[0]}</h3><p style="margin-top:10px;font-size:13px">${x[1]}</p></div>`).join('')}</div></div></section>
<section class="co">${bgs(['hangar.jpg','controlroom.jpg','cnc.jpg','blueprint.jpg'])}<div class="w"><div class="hd rv"><div><div class="eb">05 / Sectors</div><h2>Industries &amp; Sectors <em>We Support</em></h2></div><p>Our capabilities can be configured according to the technical, operational and procurement requirements of each engagement.</p></div>
<div class="sc">${['Defence & Aerospace','Government & PSU','IT & Technology','Engineering','Infrastructure','Enterprise'].map((x,i)=>`<a href="/contact/"><span class="num">0${i+1}</span><h3>${x}</h3></a>`).join('')}</div></div></section>
<section style="padding:0"><div class="two"><div class="sl" data-sl="controlroom.jpg,hangar.jpg,cnc.jpg,blueprint.jpg" data-t="Mission-critical technology and engineering support"></div><div class="rv"><div class="eb">06 / Experience</div><h2>Supporting <em>Mission-Critical</em> Requirements</h2><p style="margin-top:24px">Our team brings experience across technology, engineering, government procurement and technical manpower requirements, with exposure to organizations and ecosystems associated with Defence, Aerospace, Government and Public Sector environments.</p><div class="eb" style="color:var(--red);margin-top:30px">Selected Areas of Engagement</div>${chips(['Defence Technology','IT Infrastructure','Engineering Support','Technical Manpower','Government Procurement','GeM'])}</div></div></section>
${ctaBand('Have a Requirement? Let’s Build the Right Solution.')}`};
P['/about']=()=>`<section class="pg"><div class="w"><div class="eb">About A&amp;J</div><h1>About A&amp;J <em>Engineering Solutions</em></h1><p style="font-size:19px;margin-top:20px">Technology. Engineering. People. One integrated approach.</p></div></section>
<section style="padding-top:0"><div class="w"><div class="cg"><div class="rv"><div class="eb">01 / Profile</div><h2>Who <em>We Are?</em></h2></div><div class="rv"><p style="color:var(--text);font-size:17px">A&J Engineering Solutions is an India-based technology and engineering solutions company providing integrated services across IT infrastructure, engineering support, technical manpower, defence-oriented requirements and government procurement.</p><p>We work with organizations that require dependable technology solutions, skilled professionals and responsive execution.</p><p>Our objective is simple: understand the requirement, build the right solution and deliver with professionalism.</p><h3 style="margin-top:34px">Our Vision</h3><p style="margin-top:8px">To become a trusted technology and engineering solutions partner for organizations working on India’s most demanding technical and operational requirements.</p><h3 style="margin-top:26px">Our Mission</h3><p style="margin-top:8px">To deliver reliable solutions, skilled resources and responsive support while maintaining professional standards, transparency and long-term client relationships.</p></div></div></div></section>
<section class="co">${bgs(['blueprint.jpg','cnc.jpg','controlroom.jpg','hangar.jpg'])}<div class="w"><div class="hd rv"><div><div class="eb">02 / Company</div><h2>Company Leadership</h2></div><p>A&J Engineering Solutions is professionally managed by a leadership team with combined experience across defence, aerospace, technology and operations.</p></div>
<div class="rv" style="max-width:720px;border-top:1px solid var(--line);padding-top:26px"><span class="num">Director</span><h2 style="font-size:clamp(32px,4vw,52px)">Prince Singh</h2><p style="margin-top:16px;font-size:16px">Oversees daily operations, ensuring the company’s manufacturing and support services meet high standards of quality and efficiency.</p></div></div></section>
<section><div class="w"><div class="hd rv"><div><div class="eb">03 / Values</div><h2>Our Values</h2></div><p>The principles that shape how we work with every client and every engagement.</p></div>
${[['Integrity','We believe professional relationships are built on transparency and accountability.'],['Reliability','Our clients depend on us to respond to requirements with consistency and responsibility.'],['Technical Excellence','We continuously focus on understanding technology, engineering and evolving industry requirements.'],['Responsiveness','We believe timely communication is an essential part of successful execution.'],['Partnership','We aim to work alongside our clients rather than simply work for them.']].map((x,i)=>`<div class="si rv"><span class="num">0${i+1}</span><div><h3>${x[0]}</h3><p style="margin:0">${x[1]}</p></div></div>`).join('')}</div></section>
${ctaBand('Let’s Build the Right Solution Together.')}`;
P['/services']=()=>`<section class="pg"><div class="big" aria-hidden="true">&#9679;</div><div class="w"><div class="eb">Services</div><h1>Solutions Designed Around <em>Your Requirements</em></h1><p style="font-size:19px;margin-top:20px;max-width:640px">Integrated technology, engineering, manpower and procurement capabilities delivered with technical depth and responsive coordination.</p></div></section>
<section style="padding-top:0"><div class="w">${SV.map((s,i)=>`<div class="si rv"><span class="num">0${i+1}</span><div><h3>${s.cap}</h3><p style="margin:12px 0 0;max-width:720px">${s.all}</p>${chips(s.chips)}</div><a class="lk" href="/${s.id}/">Learn more <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></div>`).join('')}</div></section>
${ctaBand('Have a Requirement? Let’s Build the Right Solution.')}`;
const others=id=>`<section><div class="w"><div class="eb">Other Services</div><div class="ol">${SV.filter(s=>s.id!=id).map(s=>`<a href="/${s.id}/"><i>0${SV.indexOf(s)+1}</i>${s.cap}</a>`).join('')}</div></div></section>`;
const svc=s=>`<section class="pg"><div class="big" aria-hidden="true">${s.n}</div><div class="w wx"><div class="hg"><div><div class="eb">${s.lab}</div><h1 style="font-size:clamp(38px,5vw,66px);max-width:900px">${s.h}</h1><p style="font-size:18px;margin-top:22px;max-width:760px">${s.all}</p></div><div id="ss"></div></div></div></section>
<section style="padding-top:0"><div class="w">${s.secs.map(x=>x).length>1?`<div class="ls">`:`<div class="ls c3">`}${s.secs.map(x=>`<div class="rv"><h3>${x[0]}</h3><ul>${x[1].map(i=>`<li>${i}</li>`).join('')}</ul></div>`).join('')}</div>${s.note?`<p class="rv" style="margin-top:40px;font-size:17px;max-width:760px;color:var(--text)">${s.note}</p>`:''}</div></section>
${s.id=='staffing'?`<section style="padding-top:0"><div class="w"><div class="eb">Process</div><h2>How We Work</h2><p style="margin-top:14px">A structured approach from requirement to continued support.</p><div class="pr">${[['Requirement','Understand the role and technical requirement.'],['Sourcing','Identify suitable professionals.'],['Screening','Evaluate technical and professional suitability.'],['Deployment','Coordinate joining and deployment.'],['Support','Continue coordination throughout the engagement.']].map((x,i)=>`<div class="rv"><span class="num">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div></div></section>`:''}
<section class="cta"><div class="w rv"><div class="eb">${s.n} / Capability</div><h2>${s.cap}</h2><h3 style="margin-top:40px">${s.cta}</h3><p style="margin-top:10px;max-width:520px">Share your requirement and our team will respond with the appropriate solution and next steps.</p><div class="row" style="margin-top:20px"><a class="btn r" href="/requirement/">${s.cta} <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></div></div></section>${others(s.id)}`;
SV.forEach(s=>P['/'+s.id]=()=>svc(s));
P['/psu']=()=>`<section class="pg"><div class="w wx"><div class="hg"><div><div class="eb">Defence &amp; PSU</div><h1 style="font-size:clamp(38px,5vw,66px);max-width:900px">Technology &amp; Engineering for Mission-Critical Environments</h1><p style="font-size:18px;margin-top:22px;max-width:760px">${PSU_TXT}</p></div><div id="ss"></div></div></div></section>
<section style="padding-top:0"><div class="w"><div class="hd rv"><div><div class="eb">01 / Capability Areas</div><h2>Built for demanding <em>environments.</em></h2></div><p>Integrated capability areas configured around the technical and operational needs of each programme.</p></div>
<div class="g3">${[['Defence Technology','Technology solutions and support aligned with the requirements of defence-oriented programmes and establishments.'],['Engineering Support','Engineering assistance for technically demanding systems, components and project requirements.'],['Technical Manpower','Skilled engineering, IT and technical professionals for project, deputation and operational requirements.'],['IT Infrastructure','Computing, server, storage and networking infrastructure for secure and demanding environments.'],['Government Procurement','GeM cataloguing, tender documentation and procurement coordination support.'],['Project Support','Coordination, documentation and on-ground support through the lifecycle of an engagement.']].map((x,i)=>`<div class="rv"><span class="num">0${i+1}</span><h3>${x[0]}</h3><p style="margin-top:10px;font-size:13px">${x[1]}</p></div>`).join('')}</div></div></section>
<section style="padding:0"><div class="two"><div class="sl" data-sl="hangar.jpg,controlroom.jpg,cnc.jpg,blueprint.jpg" data-t="Aerospace and engineering – technology-focused support"></div><div class="rv"><div class="eb">02 / Experience</div><h2>Exposure Within <em>Critical Ecosystems</em></h2><p style="margin-top:24px">Our team has experience and exposure within ecosystems associated with defence research, aerospace and public-sector organizations, including DRDO-linked laboratories and PSU establishments.</p><p style="font-size:12px">References to these ecosystems describe experience and exposure gained by our team, and do not imply any current contractual relationship or endorsement.</p>${chips(['DRDO','PSU','Aerospace','Government','Staffing'])}</div></div></section>
${ctaBand('Discuss a Defence or PSU Requirement.')}`;
P['/contact']=()=>{return `<section class="pg"><div class="w"><div class="eb">Contact</div><h1>Let’s Start a <em>Conversation</em></h1><p style="font-size:18px;margin-top:20px;max-width:640px">Have a project, manpower requirement, technology requirement or procurement requirement? Tell us what you are looking for and our team will get back to you.</p>
<div class="cg" style="margin-top:56px"><div class="ci rv"><label>Main email</label><p><a href="mailto:hr@ajengineeringsolutions.com">hr@ajengineeringsolutions.com</a></p><label>Official email</label><p><a href="mailto:ajengineeringsolutions8@gmail.com">ajengineeringsolutions8@gmail.com</a></p><label>Contact &amp; inquiry email</label><p><a href="mailto:jay@ajengineering.in">jay@ajengineering.in</a></p><label>Phone</label><p><a href="tel:+919026224094">+91 90262 24094</a></p><label>Head Office</label><p>No. 75, Fatima Manzil, 7th Main Road, 5th Cross, Subhana Garden, Vijayanagar, Bangalore 560 040</p><label>Branch Office</label><p>Sundrewala, Near Primary School, Raipur Road, Dehradun (Uttarakhand)</p></div>
<div class="rv" style="border:1px solid var(--line);padding:34px;background:var(--panel)"><h3>Ready to share your requirement?</h3><p style="margin:14px 0 26px">Tell us what you need. Our team will understand your requirement and connect you with the appropriate solution.</p><a class="btn r" href="/requirement/">Submit your requirement <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></a></div></div></div></section>`};
P['/requirement']=()=>{const o=['Select a requirement type','IT Solution','Engineering','Defence / PSU','Manpower','GeM / Procurement','AMC / Support','Other'];return `<section class="pg"><div class="big" aria-hidden="true"><svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></div><div class="w"><div class="eb">Submit Requirement</div><h1>Submit Your <em>Requirement</em></h1><p style="font-size:18px;margin:20px 0 48px;max-width:640px">Tell us what you need. Our team will understand your requirement and connect you with the appropriate solution.</p><div style="max-width:820px"><form id="fm" class="rv"><div style="position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden" aria-hidden="true"><label for="hp">Leave this empty</label><input id="hp" tabindex="-1" autocomplete="off"></div><div><label for="a">Name</label><input id="a" required></div><div><label for="b">Company / Organization</label><input id="b"></div><div><label for="c">Email</label><input id="c" type="email" required></div><div><label for="d">Phone</label><input id="d" type="tel"></div><div class="f"><label for="e">Requirement Type</label><select id="e">${o.map((x,i)=>`<option value="${i?x:''}">${x}</option>`).join('')}</select></div><div class="f"><label for="g">Requirement Details</label><textarea id="g" rows="5"></textarea></div><div class="f"><button class="btn r" type="submit">Submit requirement <svg class="ai" viewBox="0 0 11 11" width="11" height="11" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 10L10 1M3 1h7v7"/></svg></button><p id="ok" role="status" style="margin-top:12px"></p></div></form></div></div></section>`};
/* ================= CRM CONNECTION (PASTE YOUR GOOGLE APPS SCRIPT WEB APP URL HERE) ================= */
const CRM_URL='https://script.google.com/macros/s/AKfycbwsqc1l8NEhAADXzWi_blPhHNztX8Dx-Bm7NnNTQkwy0Bjb3MuoGgA-TNhsgZKLqQHuow/exec';
/* ================= ROUTER & BEHAVIOUR ================= */
const nav=$('#nv'),mb=$('#mb');
$('#sub').innerHTML=[['/services','All Services'],...SV.map(s=>['/'+s.id,s.nav]),['/psu','Defence & PSU']].map(x=>`<li><a href="${x[0]}/">${x[1]}</a></li>`).join('');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.1});
let dvT,path=location.pathname.replace(/\/+$/,'')||'/';
function render(){clearInterval(dvT);const p=path,k=P[p]?p:'/';app.innerHTML=P[k]();scrollTo(0,0);
nav.classList.remove('o');mb.setAttribute('aria-expanded','false');
document.querySelectorAll('nav a.n').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==(k=='/'?'/':k+'/')||(k!='/'&&a.getAttribute('href')=='/services/'&&SV.some(s=>'/'+s.id==k))));
const id=k.slice(1),s=SV.find(x=>x.id==id);const m=SEO[k]||SEO['/'];document.title=m.t;const md=document.querySelector('meta[name=description]');if(md)md.content=m.d;const cn=document.querySelector('link[rel=canonical]');if(cn)cn.href=SITE+(k=='/'?'/':k+'/');
document.querySelectorAll('[data-sl]').forEach((e,k)=>slider(e,e.dataset.sl.split(',').map(i=>({img:i,t:e.dataset.t})),2500+k%3*150));
if($('#hs'))$('#hs').replaceWith(Object.assign(sliderEl(ALL.map((x,i)=>({href:'/'+x.id+'/',img:['meeting.jpg','datacenter.jpg','hangar.jpg','warehouse.jpg','hardware.jpg','controlroom.jpg'][i],t:x.t,d:x.d})),2300),{id:'hs'}));
if($('#ss')){const im=s?s.img:['controlroom.jpg','hangar.jpg','cnc.jpg','blueprint.jpg'];$('#ss').replaceWith(sliderEl(im.map(i=>({img:i,t:s?s.cap:'Defence & PSU'})),2500))}
if($('#dv')){let c=0;const set=i=>{c=i;const x=ALL[i];$('#dn').textContent='0'+(i+1)+' / What we deliver';$('#dt').textContent=x.id=='psu'?'Defence & PSU':x.t=='Defence & Engineering'?'Defence & Engineering Solutions':x.t;$('#dd').textContent=x.d;$('#dl').textContent='View '+x.t;$('#dl').href='/'+x.id+'/';document.querySelectorAll('#dv .bg').forEach((b,j)=>b.classList.toggle('on',j==i));document.querySelectorAll('.tabs button').forEach((b,j)=>b.classList.toggle('on',j==i))};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{set(+b.dataset.i);clearInterval(dvT)});set(0);dvT=setInterval(()=>set((c+1)%6),5000)}
if($('#fm'))$('#fm').onsubmit=async e=>{e.preventDefault();const f=e.target,v=i=>$('#'+i).value.trim(),ok=$('#ok'),btn=f.querySelector('button[type=submit]');if($('#hp').value)return;
if(CRM_URL.indexOf('https://script.google.com/')!==0){ok.style.color='#ffb4ad';ok.textContent='This form is not connected yet. Please email hr@ajengineeringsolutions.com or call +91 90262 24094.';return}
btn.disabled=true;ok.style.color='';ok.textContent='Sending your requirement...';
try{await fetch(CRM_URL,{method:'POST',mode:'no-cors',body:new URLSearchParams({name:v('a'),company:v('b'),email:v('c'),phone:v('d'),type:v('e'),details:v('g'),page:location.href})});f.reset();ok.style.color='#9be3b0';ok.textContent='Thank you! Your requirement has been submitted. Our team will contact you shortly.'}
catch(_){ok.style.color='#ffb4ad';ok.textContent='Sorry, we could not send your requirement. Please check your connection and try again, or email hr@ajengineeringsolutions.com.'}
finally{btn.disabled=false}};
document.querySelectorAll('.rv').forEach(e=>{const p=e.parentElement;e.style.transitionDelay=Math.min([...p.children].indexOf(e),6)*.08+'s';io.observe(e)});
document.querySelectorAll('.ls li').forEach((l,i)=>l.style.animationDelay=(i%8)*.07+.25+'s');
document.querySelectorAll('.pg h1,.hero h1').forEach(e=>sp(e,0));
(HV?document.querySelectorAll('.card,.sc a,.hero .sl'):[]).forEach(e=>{e.classList.add('tilt');e.addEventListener('mousemove',ev=>{const r=e.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width-.5,y=(ev.clientY-r.top)/r.height-.5;e.style.transition='transform .12s';e.style.transform=`perspective(900px) rotateY(${x*9}deg) rotateX(${-y*9}deg) translateZ(6px)`});e.addEventListener('mouseleave',()=>{e.style.transition='transform .5s';e.style.transform=''})});
scrl()}
function sp(el,i){[...el.childNodes].forEach(n=>{if(n.nodeType==3){const f=document.createDocumentFragment();n.textContent.split(/(\s+)/).forEach(w=>{if(!w.trim()){f.append(w);return}const o=document.createElement('span'),s=document.createElement('span');o.className='wd';s.textContent=w;s.style.animationDelay=(.35+i++*.07)+'s';o.append(s);f.append(o)});n.replaceWith(f)}else if(n.nodeType==1)i=sp(n,i)});return i}
let first=1;const cur=$('#cur');
function route(){if(first||matchMedia('(prefers-reduced-motion:reduce)').matches){first=0;render();return}cur.className='cur';void cur.offsetWidth;cur.className='cur go';setTimeout(()=>{render();app.classList.remove('ent');void app.offsetWidth;app.classList.add('ent');cur.className='cur out';setTimeout(()=>cur.className='cur',600)},380)}
function scrl(){const p=scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight);document.querySelectorAll('.big').forEach(b=>b.style.translate='0 '+scrollY*.14+'px')}
let tk=0;addEventListener('scroll',()=>{if(!tk){tk=1;requestAnimationFrame(()=>{tk=0;scrl()})}},{passive:true});
function navTo(p){if(p==path){scrollTo({top:0,behavior:'smooth'});return}path=p;try{history.pushState({},'',p=='/'?'/':p+'/')}catch(_){}route()}
addEventListener('popstate',()=>{const p=location.pathname.replace(/\/+$/,'')||'/';if(p!=path){path=p;route()}});
document.addEventListener('click',e=>{if(e.defaultPrevented||e.button||e.metaKey||e.ctrlKey||e.shiftKey)return;const a=e.target.closest&&e.target.closest('a[href^="/"]');if(!a||a.target)return;const hr=a.getAttribute('href');if(!/^\/[\w-]*\/?$/.test(hr))return;const p=hr.replace(/\/+$/,'')||'/';if(!P[p])return;e.preventDefault();const d=a.closest('.dd');if(d){d.classList.add('x');d.onmouseleave=()=>d.classList.remove('x');a.blur()}nav.classList.remove('o');mb.setAttribute('aria-expanded','false');navTo(p)});
route();
mb.onclick=()=>{const o=nav.classList.toggle('o');mb.setAttribute('aria-expanded',o)};

/* animated star particles (two depth layers, drift + twinkle + mouse parallax) */
const mob=innerWidth<700;let mx=0,my=0;
addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},{passive:true});
(()=>{const c=$('#fx'),x=c.getContext('2d');let W,H,P=[],dpr=Math.min(devicePixelRatio||1,1.5);
const rs=()=>{W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0);const n=mob?34:85;P=Array.from({length:n},(_,i)=>{const z=i%4==0?2:1;return{x:Math.random()*W,y:Math.random()*H,z,r:z==2?Math.random()*1.3+1:Math.random()*.9+.35,vx:(Math.random()-.5)*.05*z,vy:-(Math.random()*.1+.03)*z,p:Math.random()*6.28,s:Math.random()*.025+.008,h:Math.random()<.7?'150,165,255':'185,150,255'}})};rs();addEventListener('resize',rs);
let px=0,py=0,run=1;document.addEventListener('visibilitychange',()=>{run=!document.hidden;if(run)f()});
function f(){if(!run)return;x.clearRect(0,0,W,H);px+=(mx-px)*.05;py+=(my-py)*.05;
P.forEach(q=>{q.p+=q.s;q.x+=q.vx;q.y+=q.vy;if(q.y<-6){q.y=H+6;q.x=Math.random()*W}if(q.x<-6)q.x=W+6;if(q.x>W+6)q.x=-6;const a=.15+.6*Math.abs(Math.sin(q.p)),X=q.x+px*-26*q.z,Y=q.y+py*-20*q.z;
if(q.z==2){const g=x.createRadialGradient(X,Y,0,X,Y,q.r*5);g.addColorStop(0,`rgba(${q.h},${a*.7})`);g.addColorStop(1,`rgba(${q.h},0)`);x.fillStyle=g;x.fillRect(X-q.r*5,Y-q.r*5,q.r*10,q.r*10)}
x.fillStyle=`rgba(${q.h},${a})`;x.beginPath();x.arc(X,Y,q.r,0,6.283);x.fill()});
if(!matchMedia('(prefers-reduced-motion:reduce)').matches)requestAnimationFrame(f)}f()})();
if(HV){let q=0;addEventListener('pointermove',()=>{if(!q){q=1;requestAnimationFrame(()=>{q=0;document.documentElement.style.setProperty('--mx',mx.toFixed(3));document.documentElement.style.setProperty('--my',my.toFixed(3))})}},{passive:true})}
/* custom neon cursor (fine pointers only) */
if(HV&&!matchMedia('(pointer:coarse)').matches){document.documentElement.classList.add('cc');
const g=$('#cg'),ring=$('#cr'),d=$('#cd'),T=Array.from({length:6},()=>{const e=document.createElement('div');e.className='ct';document.body.append(e);return{e,x:0,y:0}});
let tx=innerWidth/2,ty=innerHeight/2,rx=tx,ry=ty,gx=tx,gy=ty,on=0;
const show=v=>{on=v;[g,ring,d].forEach(e=>e.style.opacity=v?1:0);T.forEach((t,i)=>t.e.style.opacity=v?(.34-i*.05):0)};
addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;d.style.transform=`translate3d(${tx}px,${ty}px,0)`;if(!on){rx=gx=tx;ry=gy=ty;T.forEach(t=>{t.x=tx;t.y=ty});show(1)}},{passive:true});
document.addEventListener('mouseleave',()=>show(0));document.addEventListener('mouseenter',()=>show(1));
document.addEventListener('mousedown',()=>ring.classList.add('d'));document.addEventListener('mouseup',()=>ring.classList.remove('d'));
document.addEventListener('pointerover',e=>ring.classList.toggle('h',!!e.target.closest('a,button,input,select,textarea')));
(function L(){if(!document.hidden){rx+=(tx-rx)*.16;ry+=(ty-ry)*.16;gx+=(tx-gx)*.07;gy+=(ty-gy)*.07;ring.style.transform=`translate3d(${rx}px,${ry}px,0)`;g.style.transform=`translate3d(${gx}px,${gy}px,0)`;let px=tx,py=ty;T.forEach((t,i)=>{t.x+=(px-t.x)*(.34-i*.04);t.y+=(py-t.y)*(.34-i*.04);t.e.style.transform=`translate3d(${t.x}px,${t.y}px,0) scale(${1-i*.12})`;px=t.x;py=t.y})}requestAnimationFrame(L)})()}